[general]
description = "SDL simulator for the LVGL embedded GUI framework"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
tags = ["gui", "lvgl"]
licenses = ["MIT"]

project-files = ["lvgl_ada_simulator.gpr"]


["0.0.0"]
origin = "file://.."
["0.0.0".depends-on]
sdlada = "any"
lvgl_ada = "any"
